---
- name: This is making sure that sudo in installed
  apt:
    name: sudo
    state: present

- name: Creating user group www-data if not already created
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - www-data

- name: Creating the user with name www-data
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    group: www-data
    uid: 33
  with_items:
    - www-data
...