---
- name: Install Apt from Key server
  apt_key:
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.key }}"
  with_items:
    - { keyserver: 'sks-keyservers.net', key: '0D2A45C3F1BAA57C' }

- name: Adding apt repositories.
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: "{{ item.file }}"
    update_cache: no
  with_items:
    - { repo: 'deb http://repo-cockpitproject.rhcloud.com/debian/ jessie main', file: 'cockpit.list'}
- include: updateApt.yml
...



