---
- include_vars: vars/system_users.yml

- name: Creating user group www-data if not already created
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ service_user }}"

- name: Creating the user with name www-data
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    group: www-data
    uid: 33
  with_items:
    - "{{ service_user }}"


- name: Creating the  System Default Users ****
  user:
    name: "{{ item.0 }}"
    password: "{{ item.1 }}"
    state: present
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    group: sudo
  with_together:
    - "{{ sys_user }}"
    - "{{ sys_user_pwd }}"
...