---
- include_vars:  ../vars/cockroach.yml
- name: This is making sure that sudo in installed
  apt:
    name: sudo
    state: present

- name: Creating user group if not already created
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ db_groups }}"

- name: Creating the user with name {{ db_admin }} pwd {{ db_passwd }}
  user:
    name: "{{ item }}"
    state: present
    password: "{{ db_passwd }}"
    comment: "oGod {{ item }}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    group: "{{ db_groups }}"
  with_items: "{{ db_admin }}"

