---
- name: Adding Minio connection
  command: "mc config host add minio {{minio_server}} {{access_key}} {{secret_key}} S3v4"
#  with_items:
#  # http://192.168.1.51        # BKIKJAA5BMMU2RHO6IBB    # V7f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12
#    - [ srv: "{{minio_server}}", ack: "{{access_key}}", sck: "{{secret_key}}" ]

#
# mc config host add <ALIAS> <YOUR-S3-ENDPOINT> <YOUR-ACCESS-KEY> <YOUR-SECRET-KEY> <API-SIGNATURE>
#
# mc config host add minio http://192.168.1.51 BKIKJAA5BMMU2RHO6IBB V7f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12 S3v4
#
# mc config host add gcs  https://storage.googleapis.com BKIKJAA5BMMU2RHO6IBB V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12 S3v2
#

...