---
# http://docs.ansible.com/ansible/latest/user_module.html
# Add the user 'johnd' with a specific uid and a primary group of 'admin'
- user:
    name: johnd
    comment: "John Doe"
    uid: 1040
    group: admin

# Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
- user:
    name: james
    shell: /bin/bash
    groups: admins,developers
    append: yes

# Remove the user 'johnd'
- user:
    name: johnd
    state: absent
    remove: yes

# Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
- user:
    name: jsmith
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

# added a consultant whose account you want to expire
- user:
    name: james18
    shell: /bin/zsh
    groups: developers
    expires: 1422403387
- name: This is making sure that sudo in installed
  apt:
    name: sudo
    state: present

- name: Creating user group www-data if not already created
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - www-data

- name: Creating the user with name www-data
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    group: www-data
    uid: 33
  with_items:
    - www-data
...