---
- name: Install Apt from Key server
  apt_key:
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.key }}"
  with_items:
    - { keyserver: 'keyserver.ubuntu.com', key: '93C4A3FD7BB9C367' }
- name: Adding Distro independent
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: "{{ item.file }}"
    update_cache: no
  with_items:
    - { repo: 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main', file: 'ansible'}

- include: updateApt.yml
...



