---
- name: Install Debian packages
  apt: name={{ item }} state=present
  with_items:
    - ejabberd
- name: Cloning ejabberd contributioins
  git:
    repo: git://github.com/processone/ejabberd-contrib.git
    dest: /opt/ejabberd
    clone: yes
#    version: 16.09
